// Copyright 2026 Kyiv School of Economics.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// FIPS 202 sponge for SHA3-224/256/384/512 (domain bits 01, pad10*1:
// 0x06 ... 0x80). One fully inlined sponge per back-end, generated by
// SHA3_DEFINE_SPONGE, so a back-end's lane operations are not hidden behind a
// call per lane (that would dominate the cost of a one-instruction kxor and
// distort every benchmark).

#include "sha3.h"

#include "keccak_ise.h"

static const unsigned kRate[SHA3_NUM_VARIANTS] = {144, 136, 104, 72};
static const unsigned kDigest[SHA3_NUM_VARIANTS] = {28, 32, 48, 64};
static const char *const kVariantName[SHA3_NUM_VARIANTS] = {"SHA3-224", "SHA3-256",
                                                             "SHA3-384", "SHA3-512"};
static const char *const kImplName[SHA3_NUM_IMPLS] = {"ise-kperm", "ise-shatr", "sw-rvcrypto",
                                                       "sw-xkcp-ref64", "sw-xkcp-opt64"};

// Software baselines (sw/lib/sha3_sw_*.c, vendored code under sw/vendor/).
void sha3_sw_rvcrypto_hash(unsigned rate, unsigned digest, const uint8_t *msg, size_t len,
                           uint8_t *out);
void sha3_sw_xkcp_ref64_hash(unsigned rate, unsigned digest, const uint8_t *msg, size_t len,
                             uint8_t *out);
void sha3_sw_xkcp_opt64_hash(unsigned rate, unsigned digest, const uint8_t *msg, size_t len,
                             uint8_t *out);

unsigned sha3_rate_bytes(sha3_variant_t v) { return kRate[v]; }
unsigned sha3_digest_bytes(sha3_variant_t v) { return kDigest[v]; }
const char *sha3_variant_name(sha3_variant_t v) { return kVariantName[v]; }
const char *sha3_impl_name(sha3_impl_t impl) { return kImplName[impl]; }

// Little-endian 64-bit load/store from arbitrary alignment (the build uses
// -mstrict-align, and messages are byte buffers).
static inline uint64_t load64_le(const uint8_t *p) {
    uint64_t v = 0;
    for (unsigned k = 0; k < 8; k++) v |= (uint64_t)p[k] << (8 * k);
    return v;
}

static inline void store64_le(uint8_t *p, uint64_t v, unsigned n) {
    for (unsigned k = 0; k < n; k++) p[k] = (uint8_t)(v >> (8 * k));
}

// Generates `static void <name>(rate, digest, msg, len, out)` from four
// back-end operations: INIT(), XOR_LANE(lane_index, value), PERMUTE(),
// READ_LANE(lane_index) -> uint64_t.
#define SHA3_DEFINE_SPONGE(name, INIT, XOR_LANE, PERMUTE, READ_LANE)                     \
    static void name(unsigned rate, unsigned digest, const uint8_t *msg, size_t len,     \
                     uint8_t *out) {                                                     \
        const unsigned lanes = rate / 8;                                                 \
        INIT();                                                                          \
        while (len >= rate) {                                                            \
            for (unsigned i = 0; i < lanes; i++) XOR_LANE(i, load64_le(msg + 8 * i));    \
            PERMUTE();                                                                   \
            msg += rate;                                                                 \
            len -= rate;                                                                 \
        }                                                                                \
        /* Final block: remaining bytes, then 0x06 ... 0x80 padding. */                  \
        uint8_t block[144];                                                              \
        for (unsigned k = 0; k < rate; k++) block[k] = (k < len) ? msg[k] : 0;           \
        block[len] ^= 0x06;                                                              \
        block[rate - 1] ^= 0x80;                                                         \
        for (unsigned i = 0; i < lanes; i++) XOR_LANE(i, load64_le(block + 8 * i));      \
        PERMUTE();                                                                       \
        /* Squeeze: every SHA3 digest fits in the first block of output. */              \
        for (unsigned i = 0; 8 * i < digest; i++) {                                      \
            unsigned n = (digest - 8 * i < 8) ? digest - 8 * i : 8;                      \
            store64_le(out + 8 * i, READ_LANE(i), n);                                    \
        }                                                                                \
    }

// --- Coprocessor back-ends --------------------------------------------------

static inline void keccak_kxor_lane(unsigned lane, uint64_t value) { keccak_kxor(value, lane); }

static inline void ise_shatr_permute(void) {
    for (uint64_t r = 0; r < 24; r++) keccak_shatr(r);
}

SHA3_DEFINE_SPONGE(sponge_ise_kperm, keccak_kclr, keccak_kxor_lane, keccak_kperm, keccak_krd)
SHA3_DEFINE_SPONGE(sponge_ise_shatr, keccak_kclr, keccak_kxor_lane, ise_shatr_permute, keccak_krd)

int sha3_hash(sha3_variant_t v, sha3_impl_t impl, const uint8_t *msg, size_t len,
              uint8_t *out) {
    if ((unsigned)v >= SHA3_NUM_VARIANTS) return -1;
    switch (impl) {
        case SHA3_IMPL_ISE_KPERM:
            sponge_ise_kperm(kRate[v], kDigest[v], msg, len, out);
            return 0;
        case SHA3_IMPL_ISE_SHATR:
            sponge_ise_shatr(kRate[v], kDigest[v], msg, len, out);
            return 0;
        case SHA3_IMPL_SW_RVCRYPTO:
            sha3_sw_rvcrypto_hash(kRate[v], kDigest[v], msg, len, out);
            return 0;
        case SHA3_IMPL_SW_XKCP_REF64:
            sha3_sw_xkcp_ref64_hash(kRate[v], kDigest[v], msg, len, out);
            return 0;
        case SHA3_IMPL_SW_XKCP_OPT64:
            sha3_sw_xkcp_opt64_hash(kRate[v], kDigest[v], msg, len, out);
            return 0;
        default:
            return -1;
    }
}
