#!/usr/bin/env python3
# Copyright 2026 Kyiv School of Economics.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51
"""Write docs/results/sha3-ppa.md from block-synthesis results (openspec change
sha3-cvxif-coprocessor, task 5.1).

Reads target/ihp13/yosys/block/keccak_cvxif_r<R>/metrics.json for every R in
{1, 2, 3, 4, 6} (make synth-coproc-block BLOCK=keccak_cvxif ROUNDS_PER_CYCLE=<R>)
and the R the SoC uses (iguana_pkg::KeccakRoundsPerCycle). It tabulates area,
flip-flops, critical path, slack and kperm latency, and applies the selection
rule: the largest R whose critical path leaves >= 20 % slack at the 11.0 ns
constraint. The script fails if the SoC's R is not the one the rule selects.

Usage: scripts/sha3_ppa.py [--out docs/results/sha3-ppa.md]
"""

import argparse
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
BLOCK_DIR = REPO / "target" / "ihp13" / "yosys" / "block"
ROUNDS = [1, 2, 3, 4, 6]
MIN_SLACK_FRACTION = 0.20


def soc_rounds_per_cycle():
    text = (REPO / "hw" / "iguana_pkg.sv").read_text()
    m = re.search(r"KeccakRoundsPerCycle\s*=\s*(\d+)", text)
    if not m:
        sys.exit("sha3_ppa: KeccakRoundsPerCycle not found in hw/iguana_pkg.sv")
    return int(m.group(1))


def tool_versions(r):
    log = (BLOCK_DIR / f"keccak_cvxif_r{r}" / "yosys.log").read_text(errors="replace")
    sta = (BLOCK_DIR / f"keccak_cvxif_r{r}" / "sta.rpt").read_text(errors="replace")
    yosys = re.search(r"Yosys (\S+) \(git sha1 (\w+)", log)
    opensta = re.search(r"OpenSTA (\S+ \S+)", sta)
    return (f"Yosys {yosys.group(1)} ({yosys.group(2)[:9]})" if yosys else "Yosys (unknown)",
            f"OpenSTA {opensta.group(1)}" if opensta else "OpenSTA (unknown)")


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default=str(REPO / "docs" / "results" / "sha3-ppa.md"))
    a = ap.parse_args(argv)

    rows = []
    for r in ROUNDS:
        f = BLOCK_DIR / f"keccak_cvxif_r{r}" / "metrics.json"
        if not f.exists():
            sys.exit(f"sha3_ppa: {f} missing (make synth-coproc-block BLOCK=keccak_cvxif "
                     f"ROUNDS_PER_CYCLE={r})")
        m = json.loads(f.read_text())
        if m["check_problems"] or m["structural_check_warnings"]:
            sys.exit(f"sha3_ppa: R={r} has check problems or structural warnings")
        rows.append(m)

    period = rows[0]["clock_period_ns"]
    eligible = [m["rounds_per_cycle"] for m in rows
                if m["worst_slack_ns"] >= MIN_SLACK_FRACTION * period]
    selected = max(eligible)
    soc = soc_rounds_per_cycle()
    if soc != selected:
        sys.exit(f"sha3_ppa: iguana_pkg uses R={soc}, the rule selects R={selected}")
    base = rows[0]["area_um2"]
    yosys, opensta = tool_versions(selected)

    out = [
        "# SHA-3 coprocessor PPA",
        "",
        "Generated by `scripts/sha3_ppa.py` from block-synthesis results "
        "(`make synth-coproc-block BLOCK=keccak_cvxif ROUNDS_PER_CYCLE=<R>`).",
        "",
        "## Rounds-per-cycle sweep (`keccak_cvxif`)",
        "",
        f"Stage: {rows[0]['stage']}. Corner: `{rows[0]['corner']}` (IHP SG13G2). "
        f"Constraint: {period:.1f} ns. Tools: {yosys}, {opensta}. Every row has 0 `CHECK` "
        "problems and 0 structural warnings. The block includes the 4-entry issue queue. "
        "SoC configuration for later stages: CVA6 `cv64a6_imafdcsclic_sv39`, hypervisor "
        "extension on (ADR-0004).",
        "",
        "| R | cells | area (µm²) | area vs R=1 | flip-flops | critical path (ns) | "
        f"slack @ {period:.1f} ns | `kperm` cycles |",
        "|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for m in rows:
        mark = " **(selected)**" if m["rounds_per_cycle"] == selected else ""
        out.append(f"| {m['rounds_per_cycle']}{mark} | {m['cells']:,} | {m['area_um2']:,.0f} | "
                   f"{m['area_um2'] / base:.2f}× | {m['dffs']:,} | {m['critical_path_ns']:.2f} | "
                   f"{m['worst_slack_ns']:.2f} ({m['worst_slack_ns'] / period * 100:.0f} %) | "
                   f"{m['kperm_cycles']} |")
    out += [
        "",
        f"**Selected: R = {selected}** (`iguana_pkg::KeccakRoundsPerCycle`). Rule: the "
        f"largest R whose critical path leaves ≥ {MIN_SLACK_FRACTION * 100:.0f} % slack at "
        f"{period:.1f} ns, i.e. ≥ {MIN_SLACK_FRACTION * period:.1f} ns. Eligible: "
        f"{', '.join(map(str, eligible))}.",
        "",
        "Caveats: the timing is pre-placement. Wires and placement will cut the slack, which "
        "the SoC-level place and route (task 5.4) measures. The selected R buys the shortest "
        "`kperm` for the most area: about 3.5× the R = 1 block. The per-block cycle effect is "
        "in `docs/results/sha3-ise.md`, measured at this R.",
        "",
    ]
    Path(a.out).parent.mkdir(parents=True, exist_ok=True)
    Path(a.out).write_text("\n".join(out))
    print(f"sha3_ppa: wrote {a.out} (selected R={selected})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
