#!/usr/bin/env python3
# Copyright 2026 Kyiv School of Economics.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51
"""Generate sw/vectors/sha3_kat_vectors.h from the NIST CAVP SHA-3 vectors.

Source: NIST CAVP "SHA-3 Byte Test Vectors" (sha-3bytetestvectors.zip),
pinned by SHA-256 below. The .rsp files are not vendored; this script
downloads the archive (or reads a local copy with --zip) and verifies the
hash before using it.

Selection per variant, sized for the 64 KiB SPM and the Xcelium lane timeout
(spec sha3-evaluation, "Known-answer correctness gate"):
  NIST ShortMsg: lengths 0, 1, 7, 9, rate-1 and rate bytes
                 (empty, non-multiple-of-8, and the two rate boundaries)
  NIST LongMsg:  the two shortest (2*rate+1 bytes and the next)
  derived:       rate+1 and 2*rate bytes, which no NIST file contains;
                 deterministic message bytes, digest from Python's hashlib
Every NIST digest is also cross-checked against hashlib, so the header can
only be written if both references agree.

Usage:
  scripts/sha3_vectors.py [--zip PATH]          # (re)write the header
  scripts/sha3_vectors.py [--zip PATH] --check  # exit 1 if the checked-in
                                                # header would change
"""

import argparse
import hashlib
import io
import sys
import urllib.request
import zipfile
from pathlib import Path

URL = ("https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/"
       "documents/sha3/sha-3bytetestvectors.zip")
ZIP_SHA256 = "cd07701af2e47f5cc889d642528b4bf11f8b6eb55797c7307a96828ed8d8fc8c"

OUT = Path(__file__).resolve().parent.parent / "sw" / "vectors" / "sha3_kat_vectors.h"

# (variant enum name, digest bits, rate bytes, hashlib constructor)
VARIANTS = [
    ("SHA3_224", 224, 144, hashlib.sha3_224),
    ("SHA3_256", 256, 136, hashlib.sha3_256),
    ("SHA3_384", 384, 104, hashlib.sha3_384),
    ("SHA3_512", 512, 72, hashlib.sha3_512),
]
SOURCES = ["SHA3_KAT_NIST_SHORT", "SHA3_KAT_NIST_LONG", "SHA3_KAT_DERIVED"]


def load_zip(path):
    if path:
        data = Path(path).read_bytes()
    else:
        # csrc.nist.gov answers 403 to Python's default User-Agent.
        req = urllib.request.Request(URL, headers={"User-Agent": "curl/8.7.1"})
        data = urllib.request.urlopen(req, timeout=60).read()
    digest = hashlib.sha256(data).hexdigest()
    if digest != ZIP_SHA256:
        sys.exit(f"sha3_vectors: archive SHA-256 {digest} != pinned {ZIP_SHA256}")
    return zipfile.ZipFile(io.BytesIO(data))


def parse_rsp(text):
    """Yield (len_bytes, msg bytes, md bytes) from a CAVP .rsp file."""
    entry = {}
    for line in text.splitlines():
        line = line.strip()
        if "=" not in line or line.startswith(("#", "[")):
            continue
        key, value = (s.strip() for s in line.split("=", 1))
        entry[key] = value
        if key == "MD":
            bits = int(entry["Len"])
            if bits % 8:
                raise ValueError("bit-oriented vector in a byte-oriented file")
            n = bits // 8
            msg = bytes.fromhex(entry["Msg"])[:n]  # Len = 0 carries a dummy "00"
            yield n, msg, bytes.fromhex(value)
            entry = {}


def derived_message(n, variant_index):
    return bytes((31 * i + 17 + 59 * variant_index) & 0xFF for i in range(n))


def select(zf):
    kats = []  # (variant name, source, msg, md)
    for vi, (name, bits, rate, ref) in enumerate(VARIANTS):
        short = {n: (m, d) for n, m, d in
                 parse_rsp(zf.read(f"SHA3_{bits}ShortMsg.rsp").decode())}
        long_ = sorted(parse_rsp(zf.read(f"SHA3_{bits}LongMsg.rsp").decode()))
        picks = [(n, short[n], 0) for n in (0, 1, 7, 9, rate - 1, rate)]
        picks += [(n, (m, d), 1) for n, m, d in long_[:2]]
        for n, (msg, md), src in picks:
            if ref(msg).digest() != md:
                sys.exit(f"sha3_vectors: NIST {name} len {n} disagrees with hashlib")
            kats.append((name, src, msg, md))
        for n in (rate + 1, 2 * rate):
            msg = derived_message(n, vi)
            kats.append((name, 2, msg, ref(msg).digest()))
    return kats


def c_bytes(data, indent="    "):
    if not data:
        return indent + "0x00  /* unused: empty message */"
    rows = [", ".join(f"0x{b:02x}" for b in data[i:i + 12]) for i in range(0, len(data), 12)]
    return ",\n".join(indent + r for r in rows)


def render(kats):
    out = [
        "// Copyright 2026 Kyiv School of Economics.",
        "// Licensed under the Apache License, Version 2.0, see LICENSE for details.",
        "// SPDX-License-Identifier: Apache-2.0",
        "//",
        "// GENERATED by scripts/sha3_vectors.py - do not edit. SHA-3 known-answer",
        "// vectors: a subset of NIST CAVP SHA-3 byte test vectors",
        f"// ({URL.rsplit('/', 1)[1]}, sha256 {ZIP_SHA256})",
        "// plus rate+1 / 2*rate boundary vectors with hashlib-computed digests.",
        "",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        "#include \"sha3.h\"",
        "",
        "typedef enum { " + ", ".join(SOURCES) + " } sha3_kat_source_t;",
        "",
        "typedef struct {",
        "    sha3_variant_t variant;",
        "    sha3_kat_source_t source;",
        "    uint32_t len;",
        "    const uint8_t *msg;",
        "    const uint8_t *md;",
        "} sha3_kat_t;",
        "",
    ]
    for i, (_, _, msg, md) in enumerate(kats):
        out.append(f"static const uint8_t sha3_kat_msg_{i}[] = {{\n{c_bytes(msg)}\n}};")
        out.append(f"static const uint8_t sha3_kat_md_{i}[] = {{\n{c_bytes(md)}\n}};")
    out.append("")
    out.append("static const sha3_kat_t sha3_kats[] = {")
    for i, (name, src, msg, _) in enumerate(kats):
        out.append(f"    {{{name}, {SOURCES[src]}, {len(msg)}u, sha3_kat_msg_{i}, sha3_kat_md_{i}}},")
    out.append("};")
    out.append("")
    out.append(f"#define SHA3_NUM_KATS {len(kats)}u")
    out.append("")
    return "\n".join(out)


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--zip", help="local copy of sha-3bytetestvectors.zip (default: download)")
    p.add_argument("--check", action="store_true",
                   help="do not write; exit 1 if the checked-in header differs")
    a = p.parse_args(argv)

    text = render(select(load_zip(a.zip)))
    if a.check:
        current = OUT.read_text() if OUT.exists() else ""
        if current != text:
            print(f"sha3_vectors: {OUT} is not what the generator produces", file=sys.stderr)
            return 1
        print(f"sha3_vectors: {OUT} is up to date ({text.count('sha3_kat_md_') // 2} vectors)")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    print(f"sha3_vectors: wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
